spring:
  datasource:
    url: jdbc:postgresql://localhost/store
    username: postgres
    password: "qwertygoha"
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    user:
      name: admon
      password: 123
  liquibase:
    change-log: classpath:db/changelog/dbchangelog-master.yml
server:
  port: 5000
  servlet:
    encoding:
      charset: UTF-8
jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==